sudo: false

language:
    python

python:
  - 3.5
  - 2.7

install:
  - pip install pytest-cov
  - pip install codecov

before_script: cd ./Contents/Tests

script: py.test --cov=./

after_success:
  - codecov --token=402daea0-aa6a-4dca-b448-5400fb883d38
