sudo: false

language:
    python

python:
  - 3.5
  - 3.6
  - 2.7

install:
  - pip install pytest-cov
  - pip install codecov
  - pip install ruamel.yaml

script: py.test --cov=./ --cov-config=./test/.coveragerc

after_success:
  - codecov --token=402daea0-aa6a-4dca-b448-5400fb883d38
