sudo: false

language:
    python

python:
  - 3.6
  - 2.7

install:
  - pip install pytest-cov
  - pip install codecov

script:
  - share/pymod/qa/run-tests

after_success:
  - codecov --token=402daea0-aa6a-4dca-b448-5400fb883d38
