config:

  # Do extra debug checking
  debug: false

  # Verbosity > 2 gives a lot of output
  verbose: false

  # Default shell
  default_shell: bash

  # Emit all warnings
  warn_all: true

  # Cache available modules for faster lookup.  Cache needs to be rebuilt if
  # modules are added or removed.
  cache_avail: true

  # Stop on first error encountered
  stop_on_error: true
  resolve_conflicts: false

  # Editor to open for modifying files
  editor: "vi"

  # Modules to load after calling `module purge`
  load_after_purge: null

  # Only load modules that match module name exactly. Otherwise, you can
  # specify a more qualified module name. e.g., to load ucc/1.0 you can specify
  #    module load ucc/1.0
  # or
  #    module load <path>/ucc/1.0
  # <path> need not be the full path, just a partial path.
  strict_modulename_matching: false

  # when loading devpacks, do not add the devpack module to list of loaded
  # modules.  Useful for smart MODULEPATH updating and switching.
  skip_add_devpack: false

  # Files to store collections and clones.  Paths relative to dot_dir.
  collections_filename: "collections.json"
  clones_filename: "clones.json"
  user_env_filename: "user.py"

  # Wether to colorize output, or not.  One of auto, always, never
  color: auto
