config:

  # Do extra debug checking
  debug: false

  # Verbosity > 2 gives a lot of output
  verbose: false

  # Default shell
  default_shell: bash

  # Emit all warnings
  warn_all: true

  # Stop on first error encountered
  stop_on_error: true
  resolve_conflicts: false

  # Editor to open for modifying files
  editor: "vi"

  # Modules to load after calling `module purge`
  load_after_purge: []

  # when loading devpacks, do not add the devpack module to list of loaded
  # modules.  Useful for smart MODULEPATH updating and switching.
  skip_add_devpack: false

  # Wether to colorize output, or not.  One of auto, always, never
  color: auto

  # Size of chunks used for environment variables that are serialized
  serialize_chunk_size: 200
